### ISSUE TITLE
Not working in 0.86 HA

### ISSUE THREAD

**Issue by wiuwiu** [bramkragten/custom-ui#18]
Hi.
Unfortunatelly, swipe-card and weather-card not working in 0.86 HA version.
Here is what I have on log:
`https://XXX/local/custom-lovelace/swipe-card/swipe-card.js?v=2.0.0:115:32 SyntaxError: expected dot, got '('`
and
`https://XXX/local/custom-lovelace/weather-card/weather-card.js?v=1.2.0:92:16 SyntaxError: expected dot, got '('`

**Comment by bramkragten** [comment]
They do work in 0.86.
Do you have the resources as `module`? What browser do you use?

**Comment by wiuwiu** [comment]
Hmm... Yes, resources are set as `module.` My browsers are Firefox and Chrome and I clear the cache after HA upgrade.

**Comment by bramkragten** [comment]
Browser versions?

**Comment by wiuwiu** [comment]
Chrome:  71.0.3578.98 (64-bit)
Firefox: 64.0.2 (64 bit)

**Comment by bramkragten** [comment]
For Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1342012
In Chrome it should work.

**Comment by wiuwiu** [comment]
You have the right. After re-clear the cache on Chrome everything works. On Firefox not due to the issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1342012.
