### ISSUE TITLE
Custom element doesn't exist: weather-card.

### ISSUE THREAD

**Issue by kayloehmann** [bramkragten/custom-ui#19]
Hi there, 

thanks for the great card!

I followed your documentation and get the following error with the newest version of home assistant (0.86.1):

Custom element doesn't exist: weather-card.

`{
"type": "custom:weather-card",
"entity": "weather.yourweatherentity",
"icons": "/local/custom-lovelace/weather-card/icons/"
}`

Browser: Firefox 64.0.2 (64-Bit)

**Comment by iantrich** [comment]
You have it defined in your resources section?

**Comment by kayloehmann** [comment]
Yes. Other cards also do not work. 

resources:
  - url: /local/custom-lovelace/power-wheel-card/power-wheel-card.js?v=1
    type: module
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module

Log shows: http://10.107.0.193:8123/local/custom-lovelace/weather-card/weather-card.js:92:16 SyntaxError: expected dot, got '('

**Comment by bramkragten** [comment]
Firefox doesn't work, try Chrome

**Comment by bramkragten** [comment]
See https://github.com/bramkragten/custom-ui/issues/18

**Comment by bramkragten** [comment]
If you want to use the card in Firefox, without the editor use this version: https://github.com/bramkragten/custom-ui/blob/58c41ad177b002e149497629a26ea10ccfeebcd0/weather-card/weather-card.js

**Comment by kayloehmann** [comment]
Thanks. I will play around with it a bit.

**Comment by inputsh** [comment]
Just wanna pitch in to say that you should flip `javascript.options.dynamicImport` in `about:config` and the card will work in Firefox.
