### ISSUE TITLE
Weather-card: working with 0.86.1 but current day repeating

### ISSUE THREAD

**Issue by Vayain** [bramkragten/custom-ui#20]
Hi,
weather-card is working fine for me, updated to 0.86.1 and it is still running.
Sadly the current day (FRI) is repeated for the next days in the forecast. Thanks for your work!

**Comment by bramkragten** [comment]
Are you using dark sky?

https://www.home-assistant.io/components/weather.darksky/#mode

**Comment by Vayain** [comment]
What a fast reply, thanks a lot! 
My bad, found the solution five sec. ago ;-) Changed darksky mode to daily - missed the line in your guide, my fault. ;-)
So, thanks a lot!!!
