### ISSUE TITLE
Weather-card: Failed to load resources

### ISSUE THREAD

**Issue by tamet83** [bramkragten/custom-ui#22]
Hi,

I have a problem with your custom weather card. Chrome gives me this errors:

`Failed to load resource: the server responded with a status of 404 (Not Found)
animatedcloudy.svg 
Failed to load resource: the server responded with a status of 404 (Not Found)
animatedsnowy-6.svg 
Failed to load resource: the server responded with a status of 404 (Not Found)
animatedcloudy-day-3.svg 
Failed to load resource: the server responded with a status of 404 (Not Found)
animatedrainy-5.svg 
Failed to load resource: the server responded with a status of 404 (Not Found)
09ec5360c92942c51c70.chunk.js:1032 

Unable to find icon for domain weather (sunny)
domainIcon @ 09ec5360c92942c51c70.chunk.js:1032
workbox-core.prod.js:1 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Object.<anonymous> (workbox-core.prod.js:1)
    at Generator.next (<anonymous>)
    at n (workbox-core.prod.js:1)
    at workbox-core.prod.js:1
    at <anonymous>
workbox-core.prod.js:1 

Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at Object.<anonymous> (workbox-core.prod.js:1)
    at Generator.next (<anonymous>)
    at n (workbox-core.prod.js:1)
    at workbox-core.prod.js:1
    at <anonymous>`

Actually the card doesn't have the aspetc it should.
Thanks for your help.

**Comment by bramkragten** [comment]
You miss a `/` in your icon path.

**Comment by tamet83** [comment]
> You miss a `/` in your icon path.

Ok, I'll check and let you know as soon as I get home.
Thank you

**Comment by tamet83** [comment]
You were right, my fault. Now the card is working.
Thanks for the support. Really appreciate it
