### ISSUE TITLE
Syntax error: Dynamic module import is not implemented

### ISSUE THREAD

**Issue by gijbelsy** [bramkragten/custom-ui#24]
When adding the custom weather-card to my lovelace configuration, the log outputs the following

`2019-02-17 15:22:48 ERROR (MainThread) [frontend.js.latest.201902030] https://xxx/local/custom_lovelace/weather-card/weather-card.js:92:45 SyntaxError: dynamic module import is not implemented`

**Comment by iantrich** [comment]
What browser are you on? Firefox?

**Comment by gijbelsy** [comment]
Yes, 65.0.1 x64 to be precise.

**Comment by bramkragten** [comment]
https://github.com/bramkragten/custom-ui/blob/master/weather-card/README.md#if-you-are-using-firefox
