### ISSUE TITLE
Animated Icons Not Showing Properly

### ISSUE THREAD

**Issue by nurbanasaurus** [bramkragten/custom-ui#25]
I have configured this according to the documentation and placed the icons in various locations but am not able to view these.
```
          - type: custom:weather-card
            entity: weather.thermostat
            icons: "/local/img/"
```
![weather-card_icons](https://user-images.githubusercontent.com/1489781/53144362-f92fac00-3569-11e9-89dc-13a0f3f16489.jpg)

Is there something I am missing or a module that needs to be added that is not documented?

**Comment by iantrich** [comment]
"various locations" is quite ambiguous. Did you just the suggested location in the docs?

**Comment by andy5211d** [comment]
Also trying to use this module but not getting any success.  So as above configured as per docs but think I don't have the 'entity' correct.   I'm using the Met Office weather integration so what should the entity component be;   entity: metoffice.temperature  ?

**Comment by bramkragten** [comment]
This works with weather platforms, so you would need <https://www.home-assistant.io/components/weather.metoffice/> and the entity will be something like: `weather.metoffice`

**Comment by andy5211d** [comment]
Thanks.   That got me on the right track.  Found that there are two weather platforms for Met Office, one a 'Sensor' the other 'Weather'.   Found the correct code from looking at the UI unused entities list.   If using the Weather platform then 

    entity: weather.met_office_location        *where 'location' is what has been registered with Met Office and in my case the local town or what the Met Office recognise as the local town.   

The other platform sensor is: 
      entity:sensor.met_office_weather    

Unfortunately in both cases most of the parameters set as default in your module are not available or somehow not recognised as in the 'sensor' platform nothing is displayed other then the units of measurement and for the 'weather' platform only the parameters on the left of the tile have any data,  the right hand side is just units of measurement

**Comment by bramkragten** [comment]
Please don’t hijack this issue and create your own. If you do, add some screenshots and the entity state.

**Comment by andy5211d** [comment]
Oops, will do.

**Comment by zemerick1** [comment]
I'm having the same issue. Tried the hosted way and the manual way. No icons are showing up. The card displays Ok, though.

```
resources:
  - url: /local/custom-lovelace/weather-card/weather-card.js
    type: module
```
Card definition:
```
      - entity: weather.my_ecobee3
        type: 'custom:weather-card'
        icons: /local/custom-lovelace/weather-card/icons/
        name: Weather
```

**Comment by nurbanasaurus** [comment]
Update: 
It appears like the icons "want to show" if that is appropriate phrase. It seems like the sun icon works when I glanced at it earlier, and now that it is dark outside, there is nothing to show again. It was interesting and will screencap it when I see it again.

> "various locations" is quite ambiguous. Did you just the suggested location in the docs?

I did also try to install in the suggested path. The one that is presented in the config above was last attempt at installing at the root.

> This works with weather platforms, so you would need https://www.home-assistant.io/components/weather.metoffice/ and the entity will be something like: `weather.metoffice`

I will give this a go.

**Comment by nurbanasaurus** [comment]
> Thanks. That got me on the right track. Found that there are two weather platforms for Met Office, one a 'Sensor' the other 'Weather'. Found the correct code from looking at the UI unused entities list. If using the Weather platform then
> 
> ```
> entity: weather.met_office_location        *where 'location' is what has been registered with Met Office and in my case the local town or what the Met Office recognise as the local town.   
> ```
> The other platform sensor is:
> entity:sensor.met_office_weather
> 
> Unfortunately in both cases most of the parameters set as default in your module are not available or somehow not recognised as in the 'sensor' platform nothing is displayed other then the units of measurement and for the 'weather' platform only the parameters on the left of the tile have any data, the right hand side is just units of measurement

You are correct in this, I swapped over to Dark Sky and everything appears as it should. There is an issue with Ecobee as the sensor.

> I'm having the same issue. Tried the hosted way and the manual way. No icons are showing up. The card displays Ok, though.
> 
> ```
> resources:
>   - url: /local/custom-lovelace/weather-card/weather-card.js
>     type: module
> ```
> Card definition:
> 
> ```
>       - entity: weather.my_ecobee3
>         type: 'custom:weather-card'
>         icons: /local/custom-lovelace/weather-card/icons/
>         name: Weather
> ```

Its the Ecobee.

```        cards:
          - type: custom:weather-card
            entity: weather.dark_sky
            icons: "/local/img/"
```

![animated-weather](https://user-images.githubusercontent.com/1489781/53208207-ecf82d00-3603-11e9-852b-f6de667662b2.jpg)

**Comment by zemerick1** [comment]
I have dark sky with the hosted solution. . still a no go. I'll try locally and report back.

EDIT****
Switching to Dark Sky, and moving to the local solution worked like a charm.

**Comment by bramkragten** [comment]
@nurbanasaurus Ecobee has some very weird states I believe, that it should not be using, you should create an issue for it in home assistant.

You can check the states at '/dev-state'
