### ISSUE TITLE
not working in 0.88.0

### ISSUE THREAD

**Issue by r3mcos3** [bramkragten/custom-ui#27]
card is not working 
i have this error in my lovelace and log 
![screenshot_2019-02-21 home assistant](https://user-images.githubusercontent.com/45529818/53190771-96422180-360a-11e9-9e3e-6b054fbc41cd.png)
![screenshot_2019-02-21 home assistant 1](https://user-images.githubusercontent.com/45529818/53190772-96dab800-360a-11e9-9cb6-94b506fa247a.png)

**Comment by bramkragten** [comment]
https://github.com/bramkragten/custom-ui/blob/master/weather-card/README.md#if-you-are-using-firefox

**Comment by r3mcos3** [comment]
I want to let you know that the javascript.options.dynamicimport don't exist in my about:config
i resolved the problem to disable and enable javascript in about:config

**Comment by bramkragten** [comment]
It will be in v66 and is in nightly now.
