### ISSUE TITLE
Add support for custom_updater

### ISSUE THREAD

**Issue by BenchPressesBooks** [bramkragten/custom-ui#30]
It would be extremely nice to be able to use custom_updater to track and update this card. TO do so would require publishing releases instead of just pushing code to the repo, but this would allow people to upgrade this card easier and would assist non-power users. You can either work with those devs to get this card added to their central repo, or publish your own 5 line json file that can be manually added by the users at the time they install the module to allow tracking. Let me know if this is planned/ if any assistance is required. Shouldn't require any code changes.

**Comment by iantrich** [comment]
If you use the hosted method, updates are handled for you

https://github.com/bramkragten/custom-ui/tree/master/weather-card#hosted

**Comment by BenchPressesBooks** [comment]
I guess I should have provided more information here, but this machine is running in an offline environment that is only able to connect out once a day for around 10 minutes to gather information on updates and maintenance tasks through URL whitelisted sites only. The machine is then moved off the secure enclave for updates and moved back once everything is complete. If I use the hosted method it would always be up to date but unavailable for use most of the day. I understand this is a fringe case but just thought it would be a nice addition for those who wish to go that route!

**Comment by bramkragten** [comment]
I have a json for custom updater?
https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json

**Comment by PlayedIn** [comment]
> I have a json for custom updater?
https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json

That works for me.

**Comment by BenchPressesBooks** [comment]
This can be closed, I didn't think to look at the repo root for this. Thanks for letting me know.
