### ISSUE TITLE
not working on Firefox 65

### ISSUE THREAD

**Issue by ikaroweb** [bramkragten/custom-ui#32]
Hi,
On firefox i've this error:

Custom element doesn't exist: weather-card.

{
  "type": "custom:weather-card",
  "entity": "weather.weather",
  "icons": "/local/weather-card/icons/"
}

On Safari works fine.
Thanks.

**Comment by iantrich** [comment]
https://github.com/bramkragten/custom-ui/tree/master/weather-card#if-you-are-using-firefox

**Comment by ikaroweb** [comment]
I can't find -> javascript.options.dynamicImport

**Comment by iantrich** [comment]
Just use the version without the editor...

**Comment by ikaroweb** [comment]
Yes i've tried but not work

**Comment by ikaroweb** [comment]
Now it's ok, i've cleaned the cache.
