### ISSUE TITLE
Summary available?

### ISSUE THREAD

**Issue by GoNzCiD** [bramkragten/custom-ui#37]
It should be possible to add a summary at the bottom of the card?

Thanks

**Comment by bramkragten** [comment]
What do you mean by a summary?

**Comment by GoNzCiD** [comment]
A text with a short description of the next hours/days weather.

**Comment by bramkragten** [comment]
I don't think the weather component has such a description?

**Comment by GoNzCiD** [comment]
Darksky has various summaries, for minutes, hours and days. 
[Here](https://darksky.net/dev/docs) you can see a example:
* Minutely
```JSON
"summary": "Light rain stopping in 13 min., starting again 30 min. later."
```
Hourly
```JSON
"summary": "Rain starting later this afternoon, continuing until this evening."
```
Daily
```JSON
"summary": "Mixed precipitation throughout the week, with temperatures falling to 39°F on Saturday."
```

**Comment by bramkragten** [comment]
This is a UI card for the weather platform, that should first be added to the weather platform and dark sky integration.

**Comment by GoNzCiD** [comment]
> 
> 
> This is a UI card for the weather platform, that should first be added to the weather platform and dark sky integration.

Ouch! I don't understand your previous message. Sorry, I don't know if weather component has a summary/description.

Thanks

**Comment by bramkragten** [comment]
No it doesn't... This is all that is available:

![image](https://user-images.githubusercontent.com/5662298/57706052-4d2bc780-7665-11e9-996c-86b42ac674c5.png)
