### ISSUE TITLE
[Feature Request] Compatibility with hacs ?

### ISSUE THREAD

**Issue by Bastiencc** [bramkragten/custom-ui#40]
Hi

First of all, thanks for the great works !
Custom updater will be stopped soon, HACS will replace it. it will be great if this plugin could be added to HACS (https://github.com/custom-components/hacs)

Thanks !

**Comment by vMeph** [comment]
yes plz @bramkragten  Compatibility with hacs, missing your cards,,,,

**Comment by raulvasquez** [comment]
This would be a nice addition.

**Comment by kaosmagix** [comment]
+1

**Comment by filoor** [comment]
+1

**Comment by h4nc** [comment]
+1

**Comment by bramkragten** [comment]
The following repo's can be added to HACS:

https://github.com/bramkragten/weather-card
https://github.com/bramkragten/swipe-card

**Comment by Bastiencc** [comment]
Yes it works now ! Thanks @bramkragten
