### ISSUE TITLE
Weather Card doesn't work with Home Assistant Cast

### ISSUE THREAD

**Issue by freegink** [bramkragten/custom-ui#46]
When casting using Home Assistant Cast, it shows "Custom element doesn't exist: weather-card".

From reading the FAQ page of Home Assistant Card and reading the code of weather card, it's likely related to the way how LiteElement was retrieved with weather card.

```js
const LitElement = Object.getPrototypeOf(
  customElements.get("ha-panel-lovelace")
);
```

FAQ page of Home Assistant Card:
https://cast.home-assistant.io/faq.html

**Comment by atze09** [comment]
I would also be interested in a fix of this problem.
Thanks in advance

**Comment by bramkragten** [comment]
This is fixed, but in the new repo on the weather card, will add some clarification in this repo.

https://github.com/bramkragten/weather-card/
