### ISSUE TITLE
Swipe card - very slow load (hass 0.85)

### ISSUE THREAD

**Issue by yosilevy** [bramkragten/custom-ui#7]
The following takes 30-60 sec to show. Without swiper-card it shows immediately.

- type: 'custom:swipe-card'
  cards:
  - unit: µS/cm
    detail: 2
    entity: sensor.front_garden_conductivity
    type: sensor
    graph: line
  - details: 2
    graph: line
    entity: sensor.front_garden_temperature
    type: sensor
    labels: true
    unit: C
  - details: 2
    graph: line
    entity: sensor.front_garden_moisture
    type: sensor
    unit: '%'

**Comment by yosilevy** [comment]
BTW - if you go to the edit UI and view the card in edit mode it shows immediately... :-)

**Comment by gadgetchnnel** [comment]
It looks like the issue is in the following code:

```
set hass(hass) {
        if (!this.swiper) {
            this.createSwiper(hass);
        } else {
            this._cards.forEach(item => {
                item.hass = hass;
            });

            this.swiper.update();
        }
    }
```
This only sets the **hass** property on the cards and calls the swiper.update() method the second time it is called (the first time the swiper property won't exist). Home assistant calls this method regularly (possibly every 30 seconds or so) and this causes the delay.

Changing the code to this fixes it:

```
set hass(hass) {
        if (!this.swiper) {
            this.createSwiper(hass);
        }
        
        this._cards.forEach(item => {
            item.hass = hass;
        });

        this.swiper.update();
    }
```

**Comment by bramkragten** [comment]
It will be rebuilt completly shortly, that should improve this.

**Comment by bramkragten** [comment]
Please try this beta: https://raw.githubusercontent.com/bramkragten/custom-ui/swipe-lit/swipe-card/swipe-card.js

**Comment by yosilevy** [comment]
Seems to behave the same. Shows up after a long time (even longer) and in editor all is well.

**Comment by bramkragten** [comment]
Sure you have the new version? It is about instant here...

**Comment by yosilevy** [comment]
I had an interim version which also produced JS errors. The last one works well. Thanks. 
I think you should import swiper locally like before:
`import Swiper from './js/swiper.min.js';`

I suggest you release.
